### ISSUE TITLE
Print background map

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#144]
It shall be possible to print background maps which are not OSM maps.

Especially all currently used background maps at https://maps.austrocontrol.at/mapstore shall be printabel. This includes used WMS, as well as WMTS layers. The main background map layers are:

   - Open Street Maps (already printable)
   - Basemap.at Grau
   - Basemap.at HIDPI
   - Basemap.at Orthofoto
   - OpenTopoMap
   - Stamen Toner Lite
   - NASAGIBS Night 2012

**Comment by ElenaGallo** [comment]
@offtherailz trying to print any kind of background this happens:

![errorprint](https://user-images.githubusercontent.com/56537133/95358308-35438c00-08c9-11eb-9c2a-9d3bff887089.JPG)

An error appears on the console:
> Mixed Content: The page at 'https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/new' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://austrocontrol.geo-solutions.it/austrocontrol-ms2/proxy/?url=https%3A%2F%2Faustrocontrol.geo-solutions.it%2Faustrocontrol-ms2%2Fpdf%2Fcreate.json'. This request has been blocked; the content must be served over HTTPS.

**Comment by offtherailz** [comment]
This looks to be the problem related to the https/http mismatch.
Can be solved these ways:
https://mapstore.readthedocs.io/en/latest/developer-guide/printing-module/#i-have-an-error-printing-using-reverse-proxyhttps
I think we could set a good default for our print fork to make it work in more use cases.

**Comment by offtherailz** [comment]
@ElenaGallo now it is testable again, we fixed the installation setup

**Comment by ElenaGallo** [comment]
@offtherailz now there are no printing errors but only the Open Street Map background can be printed. Other backgrounds and any type of layer (WMS, WMTS, CSW) are not printable.

**Comment by tdipisa** [comment]
Is this error affecting only the MS austrocontrol instance?

**Comment by ElenaGallo** [comment]
@tdipisa yes, only on austrocontrol

**Comment by ElenaGallo** [comment]
@offtherailz 

- [ ] OpenTopoMap and NASAGIBS Night 2012 wbackgrounds are not printable correctly.
![print2](https://user-images.githubusercontent.com/56537133/95834953-ea4ccd00-0d3d-11eb-9360-147a9d5d92a8.gif)

On console this error occurs:

> GET https://austrocontrol.geo-solutions.it/austrocontrol-ms2/pdf.worker.js 404

- [ ] The layer of the `https://sdigeo-free.austrocontrol.at/geoserver/tn-a/wms`  service (AustroControl Inspire WMS Service) is not printable and this error appears on console:

> POST https://austrocontrol.geo-solutions.it/austrocontrol-ms2/pdf/create.json 500
(anonymous) @ austrocontrol-ms2.js:7
e.exports @ austrocontrol-ms2.js:7
e.exports @ austrocontrol-ms2.js:7
Promise.then (async)
s.request @ austrocontrol-ms2.js:7
o.forEach.s.<computed> @ austrocontrol-ms2.js:7
(anonymous) @ austrocontrol-ms2.js:7
(anonymous) @ austrocontrol-ms2.js:1
(anonymous) @ austrocontrol-ms2.js:278
(anonymous) @ austrocontrol-ms2.js:278
(anonymous) @ austrocontrol-ms2.js:1
Promise.then (async)
(anonymous) @ austrocontrol-ms2.js:1
m @ austrocontrol-ms2.js:218
w @ austrocontrol-ms2.js:218
(anonymous) @ austrocontrol-ms2.js:218
O @ austrocontrol-ms2.js:218
M @ austrocontrol-ms2.js:218
C @ austrocontrol-ms2.js:218
P @ austrocontrol-ms2.js:218
gn @ austrocontrol-ms2.js:218
ue @ austrocontrol-ms2.js:218
jn @ austrocontrol-ms2.js:218
xn @ austrocontrol-ms2.js:218
Sn @ austrocontrol-ms2.js:218
t.unstable_runWithPriority @ austrocontrol-ms2.js:287
No @ austrocontrol-ms2.js:218
Ys @ austrocontrol-ms2.js:218
_n @ austrocontrol-ms2.js:218

**Comment by tdipisa** [comment]
@offtherailz can you please check it asap?

**Comment by offtherailz** [comment]
It should be testable now @ElenaGallo

**Comment by ElenaGallo** [comment]
@offtherailz the second point of [this](https://github.com/geosolutions-it/austrocontrol-C125/issues/144#issuecomment-707579125) comment is still present on austrocontrol istance

**Comment by ElenaGallo** [comment]
Closed issue, problem solved
