### ISSUE TITLE
Share map by coordinate

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#151]
_As it is already possible to [share a map based on a specified bbox](https://mapstore.readthedocs.io/en/latest/user-guide/share/), it shall also be possible to share it based on a specified coordinate combined with a scale._

_a) The coordinate shall be passed via URL (e.g. .../mapstore/#/viewer/openlayers/121?xy=16,48scale=20000)_

>The base support can be implemented leveraging on the [existing API](https://mapstore.readthedocs.io/en/latest/developer-guide/map-query-parameters/) and adding an action that adds a placemark layer, with the marker on the map.

_b) It shall be possible to create this link manually, but there shall also be a an option to share it automatically whenever a placemark is set in MapStore._

>If we want to manually edit the URL (the action API is a little verbose), we could a shortcut parameter (like bbox) but I should call it **placemark=[lon,lat]** (more clear) and use the **zoom** instead of scale( scale is rarely used in MapStore to identify level, and anyway it will be an approximation); this means that existing APIs need to be improved a bit to allow share URL less verbose than what we could do now using the existing [action dispatching system](https://mapstore.readthedocs.io/en/latest/developer-guide/map-query-parameters/#dynamically-dispatching-initial-actions-in-mapstore).

_c) The share function shall be added to the vertical button bar on the lower right, so it is also available when a GFI is opened_

>Plugins already support alternative containers (burger menu/toolbar....). We can add the possibility to use the button to trigger the share window from a toolbar button and configure austrocontrol instance to do this.

_d) The share function shall also be available on the mobile version (Hidden behind the three dots, like the zoom to extent function)_

>Hiding the toolbar button can be configured for mobile.

_e) The share button shall generate a link (in the above mentioned form) based on the currently set placemark automatically. When there is no placemark set, the above mentioned share button shall generate a link based on the current bbox._

>The existing share tool in MapStore will be improved by adding two additional advanced options alternatives to the bbox one. Enabling this options set, the user will be able to select the zoom level and edit coordinates (decimal or aeronautical) or directly click on map to automatically fill the coordinates fields: the share URL will be updated accordingly. 

_f) This link shall be able to open in MapStore on different browsers and the specified coordinate shall be indicated by a placemark when the URL is opened without further interaction. Preferably the Placemark looks like the standard placemark in MapStore._

>Once the use open a map through a new share link like that, a zoom will be performed and the map automatically centered on the provided coordinates in the URL.

**Comment by offtherailz** [comment]
Clarification:
The changes goes only in share tool.
Add an alterative option to **bbox** in advanced settings.
Something like:
- [ ] bbox 
- [ ] Center and zoom


Only one bwteen bbox and center and zoom can be enabled at the same time. Also none of them is a good choice. 
When center and zoom is enabled, you can see a form, initialized with the current center and zoom of the map: 
 - zoom (input box)
 - center a [coordinate picker (with format switch + button to click on map)]
 - [add placemark] a checkbox

The user can modify coordinates by hand or clicking on the map (using the button near the coordinate picker)

On any change on the form the URL is updated with center=[lon,lat]&zoom=zoom
if placemark is checked, an additional parameter marker=[lon,lat] with same coordinates on center
So the user can copy the URL when his changes are ok.
On window click close all handler (i.e. for click, if active) should be disabled

In query parameter epic, handle these parameters to move the map to the center and zoom indicated, and/or add a layer with the marker, if the parameter is present.

**Comment by dsuren1** [comment]
Note: The user can modify coordinates manually or click on the map and no additional button will be placed next to coordinate (except for format change button and submit button for the entered coordinates)

**Comment by ElenaGallo** [comment]
This issue is not visible in this project (it could be a configuration problem), @dsuren1 can you understand why?

**Comment by dsuren1** [comment]
> This issue is not visible in this project (it could be a configuration problem), @dsuren1 can you understand why?

Yes @ElenaGallo, it's missing project specific config for Share. https://github.com/geosolutions-it/austrocontrol-C125/pull/201 this PR should make it available in austrocontrol
