### ISSUE TITLE
Simplyfing Annotation creation and editing

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#153]
The details about the annotation refactor is in a separated PDF [[Annotations_redesign](https://drive.google.com/drive/u/0/folders/18teFXmSNF8JBqzx3YOpfoQVYp6SFO3BR)]

The re-design is mainly graphical. We need to reorganize the existing panels into the new view. All the requirements are correct and good looking. For this activity we should consider that a good part of the existing interactions, actions and controls belonging to the Annotation tool will need to be reviewed and changed to fit the new design and user interactions.

### Open Annotations

This view is the same, no changes needed

### Add Annotation

* Toolbar:  display all geometries in line and a save button on the right
* Description: Collapsible (to continue allowing rich text)

### Add Geometry

* New list of geometries, with buttons for remove, open or accept changes
* Coordinates and Style editor in accordion panel

**note**: the style on the map changes based on the accordion opened (edit style for coordinates, applied style for style accordion)

* Support Auto-save on geometry

### Annotation List

This point do not requires any change

### Edit Geometry

* When an Annotation is clicked, the editing window will be opened: according to general usages of the tool, it isn’t a good practice to directly switch in edit mode as soon as the annotation is clicked in the list (within the annotation panel), a view mode need to be activated first for consultation purposes only, then if the user has right permissions on the map, also the possibility to switch to the edit mode with a button should be provided. What we can do here is to introduce an additional configuration option (by default to false) to directly activate the edit mode once an annotation is clicked in the list

* The existing interface allows to zoom to the annotation and this detail is not present in the new mockup: we assume to maintain this functionality as it is now in the new UI, GeoSolutions will provide a new mockup 

* Two ways hover (from panel or from map) highlight of geometries when selected

* Move download annotation

### Text visualisation and style improvements

* Text Rotation: there is a separate offers for this in the estimates

* Text Style options refactor

The solution proposed by Austrocontrol seems reasonable, GeoSolutions will prepare and then share a mockup in order to agree with Austrocontrol before starting the development.

**Comment by allyoucanmap** [comment]
# Mockup

![image](https://user-images.githubusercontent.com/19175505/83897192-8d208980-a755-11ea-8416-182f4edc0e6a.png)
_initial diagram of the mockup_

Here some notes ans tests we did on the mockup thats need to be verify in development phase:

- we tried to remove the confirm button near the coordinates row so we should test if possible to directly update the geometry without an additional click. Keep in mind that the same corfirm button is needed for identify tool

current coordinates row
![image](https://user-images.githubusercontent.com/19175505/83898322-0bc9f680-a757-11ea-8573-c31b5a5eaa76.png)

mockup coordinate row
![image](https://user-images.githubusercontent.com/19175505/83898392-256b3e00-a757-11ea-8eca-08bc41a2cb07.png)

- all the select input has been updated using the `react-select` library. There were mixed select libraries in the style components

- the icon/shape picker uses the same logic of ColorPicker component. So please check ColorPicker component for development.

![image](https://user-images.githubusercontent.com/19175505/83898620-7418d800-a757-11ea-8675-69a55104b977.png)

![image](https://user-images.githubusercontent.com/19175505/83898692-8bf05c00-a757-11ea-89f2-1377e745a266.png)

![image](https://user-images.githubusercontent.com/19175505/83898567-62373500-a757-11ea-96d0-770a3090758d.png)

- label of text annotation has been moved outside of coordinate editor

![image](https://user-images.githubusercontent.com/19175505/83899086-218beb80-a758-11ea-8e8a-cf5a4ca16e24.png)

**Comment by allyoucanmap** [comment]
mockup link https://demo.geo-solutions.it/mockups/mapstore2/austrocontrol2020/#/

**Comment by allyoucanmap** [comment]
@assegnses to this issue I would like to ask to synch up with me when they will work on this issue, thanks.
Currently I'm working on some update of the style editor components and this work could be shared with the annotations style panel.
