### ISSUE TITLE
Order of Maps

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#154]
_Currently whenever a map is edited on the MapStore Welcome Page, it changes its place randomly. It is not clear how the behaviour can be influenced._

_a) It shall be possible to define the order of maps on the MapStore Welcome Home Page via Drag and Drop for the administrator only.
b) Information about the position of the map shall be stored as an additional column POSITION in the database in the table GS_STORED_DATA_

> **During the meeting we re-defined this requirement** by deciding to provide resources in alphabetical order. The requirement is that the order of records should not change when a resource (map, dashboard etc.) is created or updated; the resource order will be imposed by the database native sorting. Future improvements in MapStore (that are not part of this proposal) will allow also to sort by creation date or other properties.

**The involved activities here are:**
* Back-end default sorting on all the services for resources

**Comment by offtherailz** [comment]
A PR for this task is in review here :
https://github.com/geosolutions-it/geostore/pull/214

**Comment by tdipisa** [comment]
@offtherailz we have to fix the MapStore pom [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/pom.xml#L26) by using 1.6-SNAPSHOT, please also remember to include a release of geostore as an additional step for the next MS major release 2020.03.00.

**Comment by offtherailz** [comment]
@tdipisa The PR for austrocontrol https://github.com/geosolutions-it/MapStore2/pull/5964 already contains the update of the dependency for this project.
MapStore's one is an [independent PR ](https://github.com/geosolutions-it/MapStore2/pull/5964) that updates only mapstore.
The 1-6 snapshot is correctly deployed on maven (directory specific) and used.
