### ISSUE TITLE
Remove pink point

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#156]
Whenever a marker or start/end point of a geometry/measurement is set, a pink point and circle is shown above the symbol.  This is confusing for the user, as it can be mistaken for the specified coordinate. It shall be removed completely.

**Comment by dsuren1** [comment]
Hi @allyoucanmap 
Kindly let me know if you have a design suggestion (icon replacement) for me on approaching this particular issue.

**Comment by dsuren1** [comment]
Hi @tdipisa @allyoucanmap 
I'm proceeding with the design suggestion from @offtherailz i.e to replace the pink circle with a down arrow above the marker.
![2020-05-18 10_17_01-MapStore HomePage](https://user-images.githubusercontent.com/26929983/82175172-c7ce9900-98f0-11ea-91bf-5056c9676ca1.png)
