### ISSUE TITLE
Length Measurement - Enhancement

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#157]
The function length measurement shall be enhanced. Currently the measured length value is only shown for the whole object.

a) The length for each line segment (in the selected unit) shall be displayed between the defined coordinates.
b) The true bearing for each line segment (as defined in #145) shall be displayed between the defined coordinates. 
c) Length (in the selected unit) and bearing (as defined in #145) for each line segment shall be displayed in the map following the respective line element.
d) Length and bearing for each line segment shall also be stored when the measurement is stored as annotation
e) total length (sum of all line segments) shall remain as it is

![Measure_length](https://user-images.githubusercontent.com/1280027/77434336-fe040680-6de0-11ea-83bc-e0495d2b8d41.png)

See annotation_redesign (issue #158) for option to add an angle to text elements (the same logic must be used if possible).

**Comment by dsuren1** [comment]
Note:

- A configuration option should be added measurement, to enable the display of length and bearing as text labels in the map and in the side panel.

- The textlabel should be along the line (angle of text follow the line) in the map.

**Comment by dsuren1** [comment]
Note: The text rotation is handled in annotation.
Ref: https://github.com/geosolutions-it/MapStore2/pull/5285#issuecomment-687051919

**Comment by ElenaGallo** [comment]
@dsuren1 some notes after testing the issue:

- [ ] By changing the unit of measurement, the gray error page appears. 

*How to reproduce*

- Open a map
- Click on Burger Menu 
- Click on Measure
- Change the measure from m to km

- [ ] The gray page appears after changing Format to aeronautical and then clicking on Add New Coordinate 

*How to reproduce*
- Open a map
- Click on Burger Menu 
- Click on Measure
- Click on Format
- Click on Aeronautical
- Click on Add New Coordinate

The error on console is:

> TypeError: Cannot read property 'length' of undefined
    at i.updateMeasures (austrocontrol-ms2.js:1)
    at i.value (austrocontrol-ms2.js:1)
    at yi (austrocontrol-ms2.js:202)
    at ks (austrocontrol-ms2.js:202)
    at La (austrocontrol-ms2.js:202)
    at tl (austrocontrol-ms2.js:202)
    at $a (austrocontrol-ms2.js:202)
    at Ga (austrocontrol-ms2.js:202)
    at austrocontrol-ms2.js:202
    at t.unstable_runWithPriority (austrocontrol-ms2.js:264)
    at No (austrocontrol-ms2.js:202)
    at zo (austrocontrol-ms2.js:202)
    at Uo (austrocontrol-ms2.js:202)
    at Wa (austrocontrol-ms2.js:202)
    at _n (austrocontrol-ms2.js:202)

**Comment by dsuren1** [comment]
Note: 
Kindly test this issue after this PR is merged
https://github.com/geosolutions-it/MapStore2/pull/5938
