### ISSUE TITLE
Storing and editing measurements

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#159]
Whenever a measurement is added as an anntoation it shall be

a) added to the annoation list as it currently is done (including title and description), but additionally

b) be marked in the annotation list as a 'measurement' by adding a ruler icon to the list entry

c) automatically be named after the measurement that was conducted (Measure Bearing, Measure Area, Measure Length).

d) Whenever a stored measurement is selected for editing from the annotation list it shall not be opened in full annotation editing mode: it shall only be possible to edit title and description. (see measure_annotation_edit.png)

![Measure_annotation_edit](https://user-images.githubusercontent.com/1280027/81789199-ebb26900-9503-11ea-942a-f0e0d20c9f84.png)

e) In editing mode there shall be a button called 'Edit measurement' + respective measurement icon. When clicking this button the measurement shall be reopened in measuring mode and the user shall have the same possibilities to edit the measurement as on the initial creation.

f) Therefore it shall NOT be possible to edit geometries or (text) values of stored measurements via annotation functions, without synchronising the respective other parts of the measurement, as it currently can be done.

**Comment by tdipisa** [comment]
A review here of what provided in PR https://github.com/geosolutions-it/MapStore2/pull/5942

There should be available a new configuration (eg. **measurementEdit**) property for the annotation tool to disable the coordinates editor tab and the edit buttons in the geometry list toolbar in case of an annotation of type **measurement**

![2020_10_02_13_50_51_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/94920418-8fea7b80-04b6-11eb-81b2-10d3b4d9e519.png)

The list of annotation geometries is available so that the user can anyway click on a geometry to do some styling (only the style tab is therefore available in this case).
Regardless of this, there should be a button available in the geometry list edit toolbar to open the measurement tool as required (this button should have the same style of the other ones in the toolbar).

![2020_10_02_13_57_40_](https://user-images.githubusercontent.com/1280027/94920868-6d0c9700-04b7-11eb-97d2-42d2b1a53d70.png)

If the user clinck on that button the measurement tool is opened (with or without the coordinates editor depending on the tool configuration) so that the user can edit or redraw the measurements: clicking on save the annotation panel is re-opened with all the annotations geometries properly updated in the list.

When the measurement tool is opened only the **Add as Layer** button need to be disabled, the other ones can stay enabled so that, for example the user can also add other type of measurements to the current annotation if he wants.

**Comment by dsuren1** [comment]
@tdipisa 
Just one clarification:

- If **measurementAnnotationEdit**  is set to **true**, coordinates tab is visible along with edit measurement button and all geometries button.
And the user can **edit** the coordinates in the **coordinates panel** of **annotation** and also by clicking **edit measurement** button and edit coordinates from **measure panel** ?

**Comment by tdipisa** [comment]
Yes @dsuren1, is this a problem?

**Comment by dsuren1** [comment]
No @tdipisa . We can do it. I just want it to be clear on this scenario. Thanks

**Comment by tdipisa** [comment]
@dsuren1 

>1. Currently the geometries 'LineString and Polygon' will be exported to measurement tool along with the newly added  geometries ('LineString and Polygon') from the annotation tool. Should this be the case ?

I've reviewed a bit the requirements in [my above comment](https://github.com/geosolutions-it/austrocontrol-C125/issues/159#issuecomment-702698625) to make things easier and to avoid possible confusion to the user.

>2. Also when navigating to edit measurement tool -> make some changes/no changes -> saving the annotation, the measurement tool converts the measurement feature to geojson, so we lose the styling added from annotation. In this case do you want me to add a warning in annotation tool that the styling will be lost (when clicking on edit measurement button). (Note: Currently other annotations are lost as well)

A warning modal should opens to inform the user about that, there should be also a checkbox to avoid prompting that message next time (there are othere places where we do that in MS and localStorage is used in that case if I remember correctly).
