### ISSUE TITLE
Responsive Design - Info Box

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#160]
The following request has already been asked at our last order, but has not been implemented satisfactorily so far. The crrent solution can be seen [here ](https://maps.austrocontrol.at/mapstore/#/viewer/openlayers/121) (info box is collapsed to the lower right corner). Currently responsiveness is poor and the box size doesn't fit the content as it is a compromise solution. Therefore:

There shall be the possibility for the administrator to configure an information box with the following requirements:

a) the content of the info box shall be text, links and logos (images). Also the title of the box shall be linkable. 

b) text and links shall be configurable as it is in the text widget. It shall be possible to position images separated from the text (e.g. text align left, image align right)

b) it shall be configurable for each map individually and be independent of any layer (unlike widgets)

c) the size and position of the info box shall be defined by the administrator and shall not be restricted by a predefined raster. It shall not interfere with any existing items like zoom buttons, TOC etc. It shall especially be possible to snap it to the border of the map frame, so it is not disturbing the map view.

d) the info box shall be collaps-/expandable, but shall by default be visible whenever the map is loaded. 

e) It shall be easy for the user to close the info box. Therefore there should be an 'x' at the upper right corner

f) it must have a responsive design (avoiding scrollbars) and also work on mobile devices (collapsed, but the possibilty to show it)

g) it shall be editable by the administrator only. The user shouldn't be able to edit the info box.

**Comment by MV88** [comment]
Just FYI the [map ](https://maps.austrocontrol.at/mapstore/#/viewer/openlayers/121) linked above does not contain any details

**Comment by ElenaGallo** [comment]
@vlt1 Ops screen appears using the Details tool from Edit Properties and from Save button on Burger Menu
