### ISSUE TITLE
Central import for all MapStore exports -  Export Annotations as GeoJSON

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#164]
It is confusing for users that via 'Menu - Import data', all data types (including maps) can be imported, but importing previously exportet Annotions throws an error showing the message Unknown Geometry Type. Currently Annotations can only be Imported  via Menu - Annotations - Import annotations.

Therefore there shall be one central place to import data into MapStore.

a) 'Export data' in the main menu shall be called 'Export map' (eng) and 'Karte exportieren' (ger) in order to differentiate it from 'Import data'.

b) Via 'Import data' it shall be possible to import all data previously exported in MapStore. This includes all currently offered options (MapStore JSON configuration files, shp, KML/KMZ, GeoJSON, GPX) plus annotations

c) importing annotations shall additionally be possible in the annotations window.

**Comment by dsuren1** [comment]
**Note**: Annotation layers have a type property of "ms2-annotations" hence a separate property of "ObjectType" is not required to differentiate annotations layer from other GeoJSONs.
