### ISSUE TITLE
Selection of mulitple GFI in window

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#165]
Currently when mulitple features are clicked at the same time the user can switch between different GFI by clicking the arrows at the top right. In order to simplify selection for the user

a) a dropdown list containing all selected feature where a GFI exists shall be implemented in the header of the GFI info box. Therefore the currently existing feature title shall be changed into a dropdown list. 

b) The dropdown elements shall be ordered in the order of the layers in the TOC (see #155)

c) We suggest to use a burger menu icon to open the dropdown list due to the currently existing arrow sign in the mobile version of the GFI.

d) For the mobile version it shall still be possible to swipe through the different GFI entries.

![Dropdown_GFI a](https://user-images.githubusercontent.com/1280027/77444423-19c0da00-6dec-11ea-9d22-61d9a4f03314.png)

![Dropdown_GFI b](https://user-images.githubusercontent.com/1280027/77444657-69070a80-6dec-11ea-9090-cf356152e594.png)

**Comment by tdipisa** [comment]
Mockup available [here](https://demo.geo-solutions.it/mockups/mapstore2/get-feature-info-annotations/#/) (see changes in GFI)

**Comment by dsuren1** [comment]
**Regarding drop-down position** (placed according to mockup)
_Refer:_
https://github.com/geosolutions-it/austrocontrol-C125/issues/155#issuecomment-638219978
