### ISSUE TITLE
Update Layer Title and Description

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#168]
The title and description layers changes periodically, as we publish data every month.
MapStore does not automatically update this data, therefore a function shall be implemented to

a) update the title and description in the TOC from WMS and WMTS services for all used layers.
b) This function shall only be visible to the admin.
c) There shall be an option to update all layers at once
d) There shall be an option to update individually a single layers
e) There shall be an option to update a selection of layers (more than one, but not all)
f) The implemented function shall also give immediate feedback (warning), if the selected layers are not available in GeoServer anymore. (E.g. a layer has been implemented in MS, but the name in GeoServer has changed)

**Comment by allyoucanmap** [comment]
mockup link: https://demo.geo-solutions.it/mockups/mapstore2/austrocontrol2020/#/

![image](https://user-images.githubusercontent.com/19175505/84373752-4b706280-abdd-11ea-8fc4-f9f4a18b991e.png)

![image](https://user-images.githubusercontent.com/19175505/84373766-53300700-abdd-11ea-97cd-48977d7e1e79.png)

![image](https://user-images.githubusercontent.com/19175505/84373807-60e58c80-abdd-11ea-9036-ce5d4606cc66.png)

**Comment by tdipisa** [comment]
@vlt1 I think you still need to provide a PR to this project in order to enable in configuration what developed in MS for this issue. Can you confirm please? If yes please provide a PR soon so that we can test.

**Comment by ElenaGallo** [comment]
@vlt1 here some notes after tesing:

- The *Sentinel 2 Cloudless* layer is present by default on the Update layers window.
> https://1maps.geo-solutions.it/geoserver/s2cloudless/s2cloudless/wms?service=WMS&version=1.3.0&request=GetCapabilities

![layer_default](https://user-images.githubusercontent.com/56537133/94171490-a2026380-fe91-11ea-83ba-5227cde0ad8c.JPG)



*How to reproduce*
- Open a new map
- Click on TOC
- Click on Update layers


- The layer name is not editable manually in Layer Settings

![name](https://user-images.githubusercontent.com/56537133/94171567-b5153380-fe91-11ea-9b1e-c18a57f3c08c.JPG)
