### ISSUE TITLE
Search Service - show GFI

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#169]
When searching for features there shall be a possibility to directly show the GFI for this feature.
Preferably there shall be a button available for each search result that zooms to the feature and directly opens the GFI.
Clicking the whole bar shall still have the same effect as it has right now.

Please give us a proposal for a solution and point out possible performance impacts.

**Comment by ElenaGallo** [comment]
@vlt1 here some notes after testing this issue on austrocontrol istance:

- [ ] By enabling only the *Use button to open feature info*, the GFI button is not active even if the layer is visible on map. 
![1_GFI](https://user-images.githubusercontent.com/56537133/94790164-34e15780-03d6-11eb-8c95-f5a2ec196d47.gif)

*How to reproduce*
- Open [this](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/121) map
- On Edit search services enabel only the *Use button to open feature info*
- On TOC enabel layer visibility
- Search  'colorado' on the searching bar

**Current Result**
The GFI button is not clickable 


- [ ] By enabling the *Use button to open feature info* and the *Force search layer visibility*,  the GFI button does not open the GFI panel 
![2_GFI](https://user-images.githubusercontent.com/56537133/94790169-37dc4800-03d6-11eb-9ec8-bbb24f97591c.gif)

*How to reproduce*
- Open [this](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/121) map
- On Edit search services enabeling  the *Use button to open feature info* and the *Force search layer visibility*
- Search 'colorado' on the searching bar

**Current Result**
Clicking on the GFI button does not open the GFI panel

- [ ] By enabling only the *Use button to open feature info*, on the search bar dropdown menu the GFI button appears for a few seconds even when it is not needed  
![3_GFI](https://user-images.githubusercontent.com/56537133/94790177-3a3ea200-03d6-11eb-8dea-519df4a526e6.gif)

*How to reproduce*
- Open [this](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/121) map
- On Edit search services enabel only the *Use button to open feature info*
- Search  'colo' on the searching bar

**Current Result**
The GFI button also appears on searches that are not part of the edited service

**Comment by vlt1** [comment]
@ElenaGallo could you please open the access to the map? I've had trouble to reproduce any of the issues on my own.

**Comment by ElenaGallo** [comment]
@vlt1 now the map has permission for anonymous. In any case, if you have problems reproducing the issue just ask.

**Comment by vlt1** [comment]
@ElenaGallo I've looked through the service in the map and it seems to be for the wrong layer. The states layer in the map is not mapstore:states but topp:states and search url for it is https://demo.geo-solutions.it:443/geoserver/wfs not http://gs-stable.geo-solutions.it/geoserver/wfs. Also topp:states has properties capitalized i.e. STATE_NAME not state_name, so that has to be changed as well if working with topp:states.

**Comment by ElenaGallo** [comment]
@vlt1, you are right. Only the second point is present
