### ISSUE TITLE
Measurement tool issue with if Vincenty formula is configured

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#200]
Below is what reported by the Austrocontrol team regarding the measurement tool currently installed in the client prod environment (old MS). We need to properly check what reported in the current MS master to see if the problem still persist and fix it if needed.

_We discovered a problem with the length measurement in MapStore. I’ve tried to find out, what should happen in MapStore to get the correct length measurement as follows:_ 

_localConfig.json:_

```
"measurement": {
          "lengthFormula": "vincenty",
```

_This would be correct. In the source I found in **MapStore2/web/client/utils/CoordinatesUtils.js** the following:_

```
const geo = require('node-geo-distance');

"vincenty": (coordinates) => {

        let length = 0;

        for (let i = 0; i < coordinates.length - 1; ++i) {

            const p1 = coordinates[i];

            const p2 = coordinates[i + 1];

            const [x1, y1] = p1;

            const [x2, y2] = p2;

            length += parseFloat(geo.vincentySync({longitude: x1, latitude: y1}, {longitude: x2, latitude: y2}));

        }

        return length;

    },
```

_In https://npm.runkit.com/ I ran the following code from https://github.com/jaxgeller/node-geo-distance and looked at the results:_

```
var geo = require('node-geo-distance');

//ARP LOWI

var coord1 = {

  latitude: 47.2602777778,

  longitude: 11.3438888889

}

//ARP LOWW

var coord2 = {

  latitude: 48.1102777778,

  longitude: 16.5697222222

}

geo.vincenty(coord1, coord2, function(dist) {

  console.log(dist);

});

var vincentyDist = geo.vincentySync(coord1, coord2);

geo.haversine(coord1, coord2, function(dist) {

  console.log(dist);

});

var haversineDist = geo.haversineSync(coord1, coord2);
```

_The results are as follows (all length are in [meter]):_

```
"403478.830" (VINCENTY)

"402356.571" (HAVERSINE)
```

_The result from MapStore (ACG FREE) is: **402,356.59 m**_

_I’ve also checked the Haversine and Vincenty calculation on other web sites with the coordinates above and got the same results._ 

_Unfortunately our MapStore installation returns the Haversine calculation even if the localConfig.json holds „vincenty“._

**Comment by vlt1** [comment]
@tdipisa with this configuration:

```javascript
{
  "name": "Measure",
  "cfg": {
    "defaultOptions": {
      "showAddAsAnnotation": true,
      "showCoordinateEditor": true,
      "lengthFormula": "vincenty"
    }
  }
}
```

We get this:

![image](https://user-images.githubusercontent.com/54526151/92246240-29316c80-eece-11ea-9986-43d1c9219271.png)

Which is the correct length value.

**Comment by dsuren1** [comment]
@tdipisa 
I can confirm the same. The configuration for measure length formula in austorcontrol is now  'vincenty'
For which I get the measure length as **403478.830 m** which is as expected
![2020-09-30 18_00_22-](https://user-images.githubusercontent.com/26929983/94685446-0d8f7980-0347-11eb-99d3-b30ec67e9d50.jpg)
