### ISSUE TITLE
Bug while doing area measurement 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#215]
I found the following bug while doing an area measurement. it happens only in austrocontrol.

![measurement_bug.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/87cba933-f0b7-427c-b523-8ef14a49b226)

**Comment by dsuren1** [comment]
Note: Fix is given as part of https://github.com/geosolutions-it/MapStore2/pull/5942. Kindly test once this PR is merged
