### ISSUE TITLE
Austrocontrol Services cause en error on the austrocontrol istance

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/austrocontrol-C125#218]
## Description
The following services do not work on austrocontrol istance:

- https://sdigeo-free.austrocontrol.at/geoserver/inspire/wms

- https://sdigeo-free.austrocontrol.at/geoserver/free/wms

- https://sdimd-free.austrocontrol.at/geonetwork/srv/eng/csw-inspire

- https://sdimd-free.austrocontrol.at/geonetwork/srv/eng/csw-free

### How to reproduce

- Open a new map on MS austrocontrol istance
- Click on burger Menu
- Click on Catalog
- Search the above services

*Curret Result*
This error message appears: `There was an error loading records from the catalog` and on console: 
> Found 2 elements with non-unique id #title: (More info: https://goo.gl/9p2vKq) <select id=​"title" class=​"form-control">​…​</select>​

**Comment by offtherailz** [comment]
@randomorder let's see this in the afternoon

**Comment by kgaeb** [comment]
Dear all,

   -

   https://sdigeo-free.austrocontrol.at/geoserver/inspire/wms
   - has been changed to
   https://sdigeo-free.austrocontrol.at/geoserver/tn-a/wms
   -

   https://sdigeo-free.austrocontrol.at/geoserver/free/wms
   - should work as given
   -

   https://sdimd-free.austrocontrol.at/geonetwork/srv/eng/csw-inspire
   - has been changed to
   https://sdimd-free.austrocontrol.at/geonetwork/csw-inspire/eng/csw
   -

   https://sdimd-free.austrocontrol.at/geonetwork/srv/eng/csw-free
   - has been changed to
   https://sdimd-free.austrocontrol.at/geonetwork/csw-free/eng/csw

Kind regards
Klaus

Am Fr., 9. Okt. 2020 um 11:19 Uhr schrieb ElenaGallo <
notifications@github.com>:

**Comment by ElenaGallo** [comment]
@tdipisa sorry, the problems are not written correctly.  Adding a layer from https://sdigeo-free.austrocontrol.at/geoserver/tn-a/wms  service, this error appears on console:

> GET https://austrocontrol.geo-solutions.it/austrocontrol-ms2/proxy/?url=https%3A%2F%2Fsdigeo-free.austrocontrol.at%2Fgeoserver%2Ffree%2Fgwc%2Fservice%2Fwmts%3Fservice%3DWMTS%26REQUEST%3DDescribeDomains%26version%3D1.0.0%26layer%3DD%26tileMatrixSet%3DEPSG%253A4326%26expandLimit%3D10 404

and adding a layer from https://sdigeo-free.austrocontrol.at/geoserver/free/wms service these errors appear on console :

> Access to XMLHttpRequest at 'https://sdigeo-free.austrocontrol.at/geoserver/tn-a/gwc/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=DesignatedPoint&tileMatrixSet=EPSG:4326&expandLimit=10' from origin 'https://austrocontrol.geo-solutions.it' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> GET https://sdigeo-free.austrocontrol.at/geoserver/tn-a/gwc/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=DesignatedPoint&tileMatrixSet=EPSG:4326&expandLimit=10 net::ERR_FAILED

**Comment by tdipisa** [comment]
These are normal errors @ElenaGallo if the WMTS multidim extension is missing in the remote GeoServer. These requests are performed by MS to check if the layer has a temporal dimension: it is a feature not a bug.
