### ISSUE TITLE
Change projection problem

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/austrocontrol-C125#224]
It is not possible change  the projection of a map
![projection](https://user-images.githubusercontent.com/56537133/95981498-05dbd480-0e1f-11eb-969a-d25f046d5a86.gif)

**How to Reproduce**
- Open a new map
- Click on Select projection
- Click on EPSG 4326

*Current Result*
The projecton does not change

**Comment by vlt1** [comment]
@tdipisa From what I could gather austrocontrol defines custom resolutions array in new.json. That was specifically added in [this PR](https://github.com/geosolutions-it/austrocontrol-C125/pull/19). [This comment](https://github.com/geosolutions-it/MapStore2/blob/bd8e21bfbfb74c0cdb96f1d31d80f57d71446d07/web/client/components/map/openlayers/Map.jsx#L343) states that custom grid sets defined in mapOptions.view.resolutions are not managed by projection change. I'm not sure what that means though exactly, @offtherailz could you please explain what functionality is missing in MapStore to support this? In any case at the moment it seems MapStore does not support custom resolutions defined in mapOptions and changing projections at the same time. Are these resolutions still needed in new.json anyway?

**Comment by offtherailz** [comment]
The customer wants to have custom resolutions for its map, so I think that this resolution list is still needed. 

This is correct. `new.json` contains a set of resolutions and this partially conflicts when try to change projection. 
I think this is a structural problem: 
- We have a map with a set of resolutions fixe saved in maps (or in new.json) and this is correct.
- We want to switch projection, but the resolutions are still there. We may need to replace them or remove them when switch projection. Notice that if we remove the resolutons, when we get back to the original projections, the resolutions are lost. To avoid this I suggest that the projection switcher should allow to define a set of default resolutions for each projection it want to support, so the application is configured to work with a set of resolutions for each projection. If not defined it should be generate the defaults as usual.

Anyway I think we can disable the CRS selector for them.

**Comment by tdipisa** [comment]
@vlt1 let's disable the CRS selector for now. We can open an new issue MS side for this to provide an enhancement in the future since this is not currently an expected requirement for this project.
