### ISSUE TITLE
Client ID 1 - Share map by coordinate

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#229]
(c)(d) not implemented/configured: Sharing function is only available via menu - share. No separate button on the lower right.
Please provide information on how to configure.

(b) 
A placemark that was set by clicking on the map before opening the share function will not be visible in share function automatically. User needs to open share and activate ""Add center …"" as well as ""Add marker on loaded map"" and still gets no visual feedback that the previously clicked position is already used for sharing. Instead it is indicated that the “center of the map” is used for sharing.
E.g. open a map and click on a point at the left window side --> GFI opens and will not center map, as it doesn’t interfere with set point. Close GFI and open Share function. Activate “Add center …” and “Add Marker…” functions. You will get no feedback, that the shared point will not be the center of the map, but the previously clicked point on the left window side.

Therefore: 
- Default options for sharing function shall be: ""Add center and zoom..."" + ""Add marker ...""while currently used coordinates for the placemark shall be immediately visible on the map to user.
- Naming the function ""Add center and zoom to sharing link"" is confusing. It should be named ""Add placemark and zoom to sharing link"" as it is not always true, that the center is used. Additionally the user can click into the map and change the desired position, which again isn't always the center.
E.g. it is also possible to activate the function, click on the map, move the map so that the set placemark is out of sight, share the map believing that the ""center"" of the shown map is used, although this is not the case.

**Comment by tdipisa** [comment]
> (c)(d) not implemented/configured: Sharing function is only available via menu - share. No separate button on the lower right. Please provide information on how to configure.

We have to check is some configuration is missing.

>Default options for sharing function shall be: ""Add center and zoom..."" + ""Add marker ...""while currently used coordinates for the placemark shall be immediately visible on the map to user.

We can evaluate the cost of showing the marker as soon as the option is activated

>Naming the function "Add center and zoom to sharing link" is confusing. It should be named "Add placemark and zoom to sharing link" as it is not always true, that the center is used. Additionally the user can click into the map and change the desired position, which again isn't always the center.

If it is only a matter of changing the label it is not a problem

**Comment by michegg** [comment]
Our request included: c) The share function shall be added to the vertical button bar on the lower right, **so it is also available when a GFI is opened.** 
It wasn't clearly stated, that this is not implemented. Therefore at least visual feedback, when share function is opened after closing GFI is a needed requirement, to give the user a correct feedback about the used marking position.

**Comment by dsuren1** [comment]
**Activities to be performed:**
- Fix the vertical toolbar hidden when GFI panel is opened 
- Rename _Add center and zoom to sharing link_ to **Add placemark and zoom to sharing link**
- By default the _Add placemark and zoom to sharing link_ and _Add marker on loaded map_ should be enabled
- When _Add marker on loaded map_ is enabled, a marker should be visible on the current map to help user identify the coordinate position
- Add share to vertical toolbar

**Comment by tdipisa** [comment]
@michegg can you please confirm the above so that we can proceed with this?

**Comment by michegg** [comment]
> **Activities to be performed:**
> 
> * Fix the vertical toolbar hidden when GFI panel is opened
> * Rename _Add center and zoom to sharing link_ to **Add placemark and zoom to sharing link**
> * By default the _Add placemark and zoom to sharing link_ and _Add marker on loaded map_ should be enabled
> * When _Add marker on loaded map_ is enabled, a marker should be visible on the current map to help user identify the coordinate position
> * Add share to vertical toolbar

Correct --> while the defined default values include that marker shall be immediately visible whenever user opens the function.
