### ISSUE TITLE
Client ID 2 - Drop Down for different map views

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#230]
Function ok, . Recomm. to also hide settings for search service.
Feedback: would be more userfriendly to directly show all three search icons in search bar and instead make settings the most right icon. --> only one icon more, but easier to find for user.

**Comment by tdipisa** [comment]
> "function ok, . Recomm. to also hide settings for search service.

Which should be the logic to hide this? Only to administrator?

> Feedback: would be more userfriendly to directly show all three search icons in search bar and instead make settings the 
most right icon. --> only one icon more, but easier to find for user.

This is by design in MapStore also for layout purposes. There is nothing that we can do for this now

**Comment by michegg** [comment]
Yes, only the administrator. But we know it hasn't been a requirement so far.

**Comment by tdipisa** [comment]
> Yes, only the administrator. But we know it hasn't been a requirement so far.
