### ISSUE TITLE
Client ID 10 - Reduce space used for coordinates and buttons in GFI

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#233]
c) having the possibility to remove the info (i) sign (e.g. with a parameter in the localConfig.json) - as it is not useful for our users

ok

Please provide information on how and where to set parameters in localConfig

**Comment by tdipisa** [comment]
> Please provide information on how and where to set parameters in localConfig

We have to check this to see if a configuration is missing.

**Comment by dsuren1** [comment]
The online plugin documentation for Identify plugin is available from here with the configuration parameter for localConfig
https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Identify

**Comment by michegg** [comment]
Thanks! Issue may be closed
