### ISSUE TITLE
Client ID 13 - Remove pink point

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#236]
Why is it just replaced by another sign? Our goal was that an extra symbol is removed completely.

**Comment by tdipisa** [comment]
> Why is it just replaced by another sign? Our goal was that an extra symbol is removed completely.

As we specified in the tech proposal:
`The pink circle is the highlight system for markers, we have to design an alternative way of highlight that doesn’t confuse the users.`

Therefore it canot be completely removed without customizing the tool. That symbol appears only to highlight the point annotation to the user.

**Comment by tdipisa** [comment]
Dear @michegg, do you have further feedback for this?

**Comment by michegg** [comment]
@tdipisa it isn't an innovative or nice solution, but it's ok for the moment.
