### ISSUE TITLE
Client ID 15 - Display and renaming of Bearing

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#237]
a) by default be displayed by values from 000 - 360°, but it shall also be possible to display decimal places (e.g. 000,00 - 359,99). The number of visible decimal places shall be configurable in the localConfig.json

Please provide information on how and where to set parameters in localConfig

""T"" after value should be removed in all elements of measure function (map, dropdown and display between coordinates), as tooltip already informs about measurement based on true north.

**Comment by tdipisa** [comment]
>a) by default be displayed by values from 000 - 360°, but it shall also be possible to display decimal places (e.g. 000,00 - 359,99). The number of visible decimal places shall be configurable in the localConfig.json

>Please provide information on how and where to set parameters in localConfig

We have to check if all is properly updated in the plugin documentation. We will get back to you soon.

>""T"" after value should be removed in all elements of measure function (map, dropdown and display between coordinates), as tooltip already informs about measurement based on true north.

We will evaluate the cost of this to check if it can be done quickly.

**Comment by dsuren1** [comment]
> a) by default be displayed by values from 000 - 360°, but it shall also be possible to display decimal places (e.g. 000,00 - 359,99). The number of visible decimal places shall be configurable in the localConfig.json

The documentation for configuring the true bearing with fractional digits in localConfig is available [here](https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Measure)

> 
> ""T"" after value should be removed in all elements of measure function (map, dropdown and display between coordinates), as tooltip already informs about measurement based on true north.

**Question**
1.  So the measurement value to be displayed (_example_: **056°**)
![2020-11-30 16_04_58_edited](https://user-images.githubusercontent.com/26929983/100599603-3d96d100-3326-11eb-8de4-421a4ab929d1.jpg)

2. Should we remove ""T"" from annotations as well?
![2020-11-30 16_08_36 MapStore2 Project](https://user-images.githubusercontent.com/26929983/100599824-82bb0300-3326-11eb-85a9-9c319ee2bd00.jpg)

**Comment by tdipisa** [comment]
@michegg can you please provide some feedback for the above comment?

**Comment by michegg** [comment]
> > a) by default be displayed by values from 000 - 360°, but it shall also be possible to display decimal places (e.g. 000,00 - 359,99). The number of visible decimal places shall be configurable in the localConfig.json
> 
> The documentation for configuring the true bearing with fractional digits in localConfig is available [here](https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Measure)
> 
Thank you! Its working fine.

> > ""T"" after value should be removed in all elements of measure function (map, dropdown and display between coordinates), as tooltip already informs about measurement based on true north.
> 
> **Question**
> 
> 1. So the measurement value to be displayed (_example_: **056°**)
>    ![2020-11-30 16_04_58_edited](https://user-images.githubusercontent.com/26929983/100599603-3d96d100-3326-11eb-8de4-421a4ab929d1.jpg)

Yes, example 056° is correct.
Remove it from all the places mentioned above and also from displayed values for distance and area measurement in map and list/info in right panel. --> make sure it's consistent throughout all functions.

> 2. Should we remove ""T"" from annotations as well?
>    ![2020-11-30 16_08_36 MapStore2 Project](https://user-images.githubusercontent.com/26929983/100599824-82bb0300-3326-11eb-85a9-9c319ee2bd00.jpg)

Yes. Annotations shall be displayed in the same way, as the measurement itself.
