### ISSUE TITLE
Client ID 16 - Length Measurement - Enhancement

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#238]
(c) enable style option to follow line - not implemented

- Tooltip for advantage/disadvantage of add layer vs. Annotation highly recommended! The two options are confusing for the user.

- Is it possible to set default text size in local config? Its a little bit small.

- ""T"" should also be removed, as in measure bearing (client ID 15).

**Comment by tdipisa** [comment]
> (c) enable style option to follow line - not implemented

> Tooltip for advantage/disadvantage of add layer vs. Annotation highly recommended! The two options are confusing for the user.

There aren't disadvantages or advantages: they are two different options for different purposes: one to convert a measurement into an annotation while the other to convert it into a simple layer in TOC. This is a new feature we recetly introduced.
Please let us know which kind of tooltip you what to use for both, otherwise we will check to remove one of them by configuration

>Is it possible to set default text size in local config? Its a little bit small.

Currently is is not possible

>  "T" should also be removed, as in measure bearing (client ID 15).

I already replied in #237 for this

**Comment by michegg** [comment]
Would it be a solution to turn the label by a calculation based on the measured degree?
 
Suggestion for tooltip: 

- EN: "Add as layer: measurement will be added to list of layers and cannot be edited again."
- GER: "Als Layer hinzufügen: Messung wird zur Ebenenliste hinzugefügt und kann nicht mehr bearbeitet werden."
- EN: "Add as annotation: measurement will be added to list of annotations and can be edited again."
- GER: "Als Zeichnung/Notiz hinzufügen: Messung wird zur Liste der Zeichnungen/Notizen hinzugefügt und kann erneut bearbeitet werden."

**Comment by tdipisa** [comment]
> Would it be a solution to turn the label by a calculation based on the measured degree?

What do you mean precisely? Can you please clarify better?

> Suggestion for tooltip:
> 
> * EN: "Add as layer: measurement will be added to list of layers and cannot be edited again."
> * GER: "Als Layer hinzufügen: Messung wird zur Ebenenliste hinzugefügt und kann nicht mehr bearbeitet werden."
> * EN: "Add as annotation: measurement will be added to list of annotations and can be edited again."
> * GER: "Als Zeichnung/Notiz hinzufügen: Messung wird zur Liste der Zeichnungen/Notizen hinzugefügt und kann erneut bearbeitet werden."

We can evaluate to update [your translations files](https://github.com/geosolutions-it/austrocontrol-C125/tree/DEV/translations) for this, since they can be easily overridden in a MS project.

**Comment by michegg** [comment]
> > Would it be a solution to turn the label by a calculation based on the measured degree?
> 
> What do you mean precisely? Can you please clarify it better?
> 
It should be possible to rotate a label by a certain degree. By default the value is 0 (at least in geoserver) and based on the knowledge, that the labels orientation in the map equals a 90° true bearing line it should be possible to use this variables in a calculation to rotate the label (values x between 1-180 shall be rotated by x-90, values from 181-359 by x-270, while x is known, because it's measured).
Maybe this evades the problems with curves and at least simulates a label along the line.
But don't put too much effort in it. Simple labels are also acceptable.

> > Suggestion for tooltip:
> > 
> > * EN: "Add as layer: measurement will be added to list of layers and cannot be edited again."
> > * GER: "Als Layer hinzufügen: Messung wird zur Ebenenliste hinzugefügt und kann nicht mehr bearbeitet werden."
> > * EN: "Add as annotation: measurement will be added to list of annotations and can be edited again."
> > * GER: "Als Zeichnung/Notiz hinzufügen: Messung wird zur Liste der Zeichnungen/Notizen hinzugefügt und kann erneut bearbeitet werden."
> 
> We can evaluate to update [your translations files](https://github.com/geosolutions-it/austrocontrol-C125/tree/DEV/translations) for this, since they can be easily overridden in a MS project.

In case you won't use this for standard MapStore, we will change the translation files ourselves on our local installation.

**Comment by tdipisa** [comment]
Dear @michegg, 

>It should be possible to rotate a label by a certain degree. By default the value is 0 (at least in geoserver) and based on the knowledge, that the labels orientation in the map equals a 90° true bearing line it should be possible to use this variables in a calculation to rotate the label (values x between 1-180 shall be rotated by x-90, values from 181-359 by x-270, while x is known, because it's measured).
Maybe this evades the problems with curves and at least simulates a label along the line.

Unfortunately we can't do much about it at the moment, considering the mapping library limitations, without introducing a customization.

>But don't put too much effort in it. Simple labels are also acceptable.

If the implemented solution is anyway acceptable for you, I wouldn't like to proceed with a customization as specified above.

> Suggestion for tooltip: 
> 
> - EN: "Add as layer: measurement will be added to list of layers and cannot be edited again."
> - GER: "Als Layer hinzufügen: Messung wird zur Ebenenliste hinzugefügt und kann nicht mehr bearbeitet werden."
> - EN: "Add as annotation: measurement will be added to list of annotations and can be edited again."
> - GER: "Als Zeichnung/Notiz hinzufügen: Messung wird zur Liste der Zeichnungen/Notizen hinzugefügt und kann erneut bearbeitet werden."

We will proceed on updating the translations on your project. Thank you.

**Comment by michegg** [comment]
@tdipisa yes, the solution is ok for the moment.

**Comment by dsuren1** [comment]
@michegg 
The translation texts are too big for a tooltip to accommodate in the measure panel. It would be nice if you could give us a short and precise text.
![2020-12-01 14_38_30-AustroControl Custom MapStore2 Project](https://user-images.githubusercontent.com/26929983/100719701-fc182b80-33e2-11eb-92c4-efc1491519dc.jpg)

**Comment by michegg** [comment]
@dsuren1 please try
EN: "Add as layer (measurement cannot be edited again)"
GER: "Als Layer hinzufügen (Messung kann nicht mehr bearbeitet werden)"
EN: "Add as annotation (measurement can be edited again)"
GER: "Als Notiz hinzufügen (Messung kann erneut bearbeitet werden)"

If still too long remove "measurement" and "Messung" within the brackets. (e.g. Als Layer hinzufügen (kann nicht mehr bearbeitet werden).
Otherwise please provide me an approx. number of max. characters.

**Comment by dsuren1** [comment]
@michegg 
These texts should fit perfectly fine. I will make the changes accordingly. Thanks

**Comment by dsuren1** [comment]
> If still too long remove "measurement" and "Messung" within the brackets. (e.g. Als Layer hinzufügen (kann nicht mehr bearbeitet werden).

Just to be clear (For testers). 
Translation text implemented will be these as per suggestion.
EN: "Add as layer (Cannot be edited again)"
GER: "Als Layer hinzufügen (Kann nicht mehr bearbeitet werden)"
EN: "Add as annotation (Can be edited again)"
GER: "Als Notiz hinzufügen (Kann erneut bearbeitet werden)"
