### ISSUE TITLE
Client ID 17 - Storing and editing measurements

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#239]
Once a measurement is finished (e.g. by double clicking) or after reopening it from annotations it is not possible to select and edit it via the graphical view (only via adding coordinates in editor). Instead when clicking in the map a new mesurment is started. This is not visible for the user, because the dropdown menu always stays on the first element. 

Expectation.: Dropdown always shows currently edited measurement + click on element in map enables to add new vertices via click in map.

**Comment by tdipisa** [comment]
> Once a measurement is finished (e.g. by double clicking) or after reopening it from annotations it is not possible to select and edit it via the graphical view (only via adding coordinates in editor). Instead when clicking in the map a new mesurment is started. This is not visible for the user, because the dropdown menu always stays on the first element.

> Expectation.: Dropdown always shows currently edited measurement + click on element in map enables to add new vertices via click in map.

We have maintained the same behavior for editing the measurements through the form: it was not possible to edit the measurements by editing the geometries directly in the map and it is the same now.
There wasn't a specific requirement for this new behavior you are mentioning:
_... the user shall have the same possibilities to edit the measurement as on the initial creation._

**Comment by michegg** [comment]
On the initial creation it is possible to define the measurement by clicking on the map, therefore "the user shall have the same possibilities to edit the measurement as on the initial creation."
includes having the possibility to edit measurements by clicking into the map.

Our main problem is, that there is no intuitive way to add a vertex or edit/move an existing one. Even if the user adds a new vertex by pressing (+) it's not possible to define this vertex via click on the map. The user always needs to use the textual input fields.

As a user I would expect the following behavior
Editing:
	1. start editing from saved annotation
	2. select the measuring element I want to edit in the drop down list. (Ideally it would also be possible to select it in the map, like for annotations)
		a. (ideally selected entry is highlighted in map)
		b. existing vertices for selected entry can be dragged and dropped inside the map
		c. by clicking somewhere else in the map a new vertex is added. The direct line between last vertex of selected measurement and mouse position is indicated by a dashed line. (option: it should at least be possible to define a new vertex (including the dashed line) in the map after the (+) button has been clicked.)
	3. There is a button (next to the dropdown list) that enables to add a new measurement.

Therefore behaviour on initial creation should be:
	1. add first measurement by clicking in the map (as now)
	2. double click to store defined vertices and show them in measuring window (as now)
	3. remain in editing mode for currently created measurement and enable behaviour as described in Editing 2.b and 2.c (drag and drop vertices and add vertex by clicking somewhere else, indicated by a dashed line)
	4. add a new measurement by pressing a respective button.



**Currently there are also some other issues:**

- 	when starting editing mode from a saved measuring annotation, the user defines a new measuring by clicking into the map. After a double-click the measurement is finished, but the dropdown + display of coordinates is not updated to display the new measurement. It shows the last active entry.
- 	Potential bug: you have to click three times to finish a bearing measurement. Is there a special reason for that?

**Comment by tdipisa** [comment]
Dear @michegg I'm sorry for the late answer on this.

>On the initial creation it is possible to define the measurement by clicking on the map, therefore "the user shall have the same possibilities to edit the measurement as on the initial creation."
includes having the possibility to edit measurements by clicking into the map.

We were pretty sure we understood the requirements correctly. The text below in the requirements:

"_When clicking this button the measurement shall be reopened in measuring mode and the user shall have the same possibilities to edit the measurement as on the initial creation._"

it was interpreted by us as maintaining exactly the same editing capabilities of the initial creation, where the editing of existing geometries on map is available only through the form and not by interacting with the map. Also our estimates are reflecting this. 

Just to be clear we had made a note in the technical proposal to highlight that point in relation to our estimates.

>Note: actually you can not edit the measurement on map, only add coordinates writing latitude and longitude and switching coordinate order, this will remain the same.

Providing the editing capabilities you have reported in the above comment requires a significant effort, therefore we cannot refactor the implementation at this stage, I'm sorry.

Regarding the other points you reported:

> when starting editing mode from a saved measuring annotation, the user defines a new measuring by clicking into the map. After a double-click the measurement is finished, but the dropdown + display of coordinates is not updated to display the new measurement. It shows the last active entry.

This is probably something we can improve now. Please let me check it with our developers.

>Potential bug: you have to click three times to finish a bearing measurement. Is there a special reason for that?

Unlike the other measurement types, to finish a bearing measurement, just one single click is needed. I've tested it again on Edge, FF and Chrome and it seems working fine. Do you have further info to be able to replicate?

**Comment by michegg** [comment]
> Providing the editing capabilities you have reported in the above comment requires a significant effort, therefore we cannot refactor the implementation at this stage, I'm sorry.

That's ok for now.

>This is probably something we can improve now. Please let me check it with our developers.

Yes, please check this.

>Unlike the other measurement types, to finish a bearing measurement, just one single click is needed. I've tested it again on Edge, FF and Chrome and it seems working fine. Do you have further info to be able to replicate?

Thanks for the explanation! I tried to double click, which kept me in measuring mode and my next reflex was to click three times. Of course one click works as well, so no further investigation needed.

**Comment by tdipisa** [comment]
@michegg I've created https://github.com/geosolutions-it/MapStore2/issues/6291 in MS for the following point:

>when starting editing mode from a saved measuring annotation, the user defines a new measuring by clicking into the map. After a double-click the measurement is finished, but the dropdown + display of coordinates is not updated to display the new measurement. It shows the last active entry.

@AGMETEOR will work on this soon.
