### ISSUE TITLE
Client ID 18 - Legend size

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#240]
- (a) not implemented: a) The legend shall by default be displayed in the size as defined in GeoServer (Styles - Legend - Width and Height)

**Comment by tdipisa** [comment]
>- (a) not implemented: a) The legend shall by default be displayed in the size as defined in GeoServer (Styles - Legend - Width and Height)

We will check if we have a configuration option for this purpose.

**Comment by tdipisa** [comment]
Dear @michegg, for this we did what present and agreed in the tech proposal, also reported in the original issue [here](https://github.com/geosolutions-it/austrocontrol-C125/issues/146#issue-586840138):

> **Below the involved activities for this work:**
> 
> - Allow to customize width and height of the layer’s legend (putting these additional configuration properties in General tab maybe is more appropriate that in Style tab)
> - Store the settings for legend size in map context file
> - Make the legend using the configured size: it will fit at least the max-width of the TOC of course

It is necessary to have at least a default available to prevent layout issues.

**Comment by michegg** [comment]
@tdipisa it is not explicitly mentioned in the tech proposal, that (a) will not be implemented and also wasn't discussed with us.
Having a default value doesn't exclude the possibility to set a value based on GeoServer settings (and if necessary adapt it to the layout).

Nevertheless this is not one of our top priorities for now and may be postboned.
