### ISSUE TITLE
Client ID 20 - Responsive Design - Info Box

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#242]
- Not shown as i-sign in toolbar (specified in technical proposal)
- Not shown on mobile devices
- Right align for image doesn't work (It is correclty shown in editing mode, but not saved)
- Size of modal info box is not responsive, but has a fixed size. Therefore there may be a lot of whitespace.

**Comment by tdipisa** [comment]
>Not shown as i-sign in toolbar (specified in technical proposal)

We have to check if some configuration is missing for this and if the documentation is properly updated.

>Not shown on mobile devices

We have to check if some configuration is missing for this and if the documentation is properly updated.

>Right align for image doesn't work (It is correclty shown in editing mode, but not saved)

This is a bug we have to fix

>Size of modal info box is not responsive, but has a fixed size. Therefore there may be a lot of whitespace.

This point is not so clear to us. the Info box properly fits the browser window size when it is resized. Can you please clarify it better? Can you provide a screenshot so that we are able to reproduce?

**Comment by michegg** [comment]
The window doesn't adapt to it's content. Therefore it happens that there is a lot of whitespace, if there is few content.
![Screenshot_Info](https://user-images.githubusercontent.com/57953447/100099741-27899c00-2e60-11eb-9890-d61a3d943d87.PNG)

**Comment by tdipisa** [comment]
I'm not so sure at the moment we can have control on the height, I will ask developers for this.
