### ISSUE TITLE
Client ID 22 - Max zoom level for  search service / zoom to extent

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#244]
UI ok
Please provide information on how and where to set parameters in localConfig

**Comment by tdipisa** [comment]
> UI ok
Please provide information on how and where to set parameters in localConfig

Ok we will check to provide this soon.

**Comment by dsuren1** [comment]
@michegg 
You don't need to set any configuration from localConfig as max zoom is configurable from the application itself while configuring your search service and the documentation for the same is available [here ](https://mapstore.readthedocs.io/en/latest/user-guide/menu-bar/#configuring-a-search-service)
Kindly let me know if you need anything on the same.

**Comment by michegg** [comment]
> @michegg
> You don't need to set any configuration from localConfig as max zoom is configurable from the application itself while configuring your search service and the documentation for the same is available [here ](https://mapstore.readthedocs.io/en/latest/user-guide/menu-bar/#configuring-a-search-service)

already tested this - it's working fine
> Kindly let me know if you need anything on the same.

I was searching for a possibility to set the max zoom level for zoom to extent and locate me function and found that we agreed on including it [here ](https://github.com/geosolutions-it/MapStore2/blob/00929965390115e5d2fa26c952dffbdf7d32336d/web/client/epics/search.js#L129) - still need to test this.
Please provide information on how to set if maxZoom is valid for all features or just point features as stated in 
_a) This max scale shall always be used for point features._
_b) There shall be an option to activate the max scale also for line and polygon feature._
_e) ... as a parameter ""maxZoomScale"" (numerical value for
scale) and ""useMaxZoom"" (values: ""pointFeatures"", ""allFeatures"")_

**Comment by dsuren1** [comment]
> I was searching for a possibility to set the max zoom level for zoom to extent and locate me function and found that we agreed on including it [here ](https://github.com/geosolutions-it/MapStore2/blob/00929965390115e5d2fa26c952dffbdf7d32336d/web/client/epics/search.js#L129) - still need to test this.

Setting the max zoom from the search service config panel will be used to automatically set the max zoom for the zoom to extent 
[here ](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/search.js#L131)

**Comment by michegg** [comment]
> > I was searching for a possibility to set the max zoom level for zoom to extent and locate me function and found that we agreed on including it [here ](https://github.com/geosolutions-it/MapStore2/blob/00929965390115e5d2fa26c952dffbdf7d32336d/web/client/epics/search.js#L129) - still need to test this.
> 
> Setting the max zoom from the search service config panel will be used to automatically set the max zoom for the zoom to extent
> [here ](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/search.js#L131)

Ok, but what happens if different zoom values are set for max zoom level of different search services? And which value will be used for zoom to extent and locate me, if no search service is configured at all?

> e) ... as a parameter ""maxZoomScale"" (numerical value for
> scale) and ""useMaxZoom"" (values: ""pointFeatures"", ""allFeatures"")

Still needed: parameter to define if all features are using the maxzoomlevel, or only point features

**Comment by tdipisa** [comment]
@michegg the zoom behavior is managed by MapStore and it depends also on the feature type (point, polygon, line)

- Each search service has its own max zoom level: this means that when you click on a item in the search list, the search tool uses the max zoom level value set for the related search service the item belongs to.

- The zoom logic anyway consider also the type of the geometry corresponding to the clicked element in the search list:
   - In case of lines or polygons, MapStore, in case of a higher "max zoom level" set, will zoom anyway the map by choosing the closest zoom level to fit the geometry in the viewport extent. So if you, in [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358) for example, set the max zoom level of the US States search service to 30, MapStore will anyway zoom the map to the closest zoom level that fits the polygon (the same happens for lines):

![search_service](https://user-images.githubusercontent.com/1280027/101065331-50630d00-3595-11eb-84e5-15918f73cf46.gif)

   - In case of points, MapStore will zoom everytime to the exact max zoom level set in the service.

![search_service_point](https://user-images.githubusercontent.com/1280027/101065962-17776800-3596-11eb-862e-7b214b02e611.gif)

**Comment by michegg** [comment]
@tdipisa the behavior of search service max zoom level is clear to me. Those settings are stored in the localConfig, which is perfectly fine for us.

But we also requested the max zoom level parameter for _"all zoom to extent functions and the "locate me" operation"_ (e.g. in the attribute table it is possible to zoom to each data entry separately) and an option to disable the usage of the parameter for line and polygon features "_b) There shall be an option to activate the max scale also for line and polygon feature._".

In the technical proposal you suggested to implement the functions directly in [search.js](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/search.js#L131) instead of localConfig.
As @dsuren1 wrote:
>Setting the max zoom from the search service config panel will be used to automatically set the max zoom for the zoom to extent
[here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/search.js#L131)

Therefore it is open to us:

- which max zoom level is used for all zoom to extent functions (except the search service) and the "locate me" operation, when there is no search service set at all?
- which max zoom level is used for all zoom to extent functions (except the search service) and the "locate me" operation, when for different search services different max zoom values are set?

- is the possibility to disable the max zoom level for polygon and line features implemented anywhere?


Our expectation was to set only one parameter for max zoom level in the locaConfig which serves the search, zoom to and locate me function (and may be overwritten by individual settings for search service).

**Comment by tdipisa** [comment]
@michegg thank you so much for clarifying your above comments.

>But we also requested the max zoom level parameter for "all zoom to extent functions and the "locate me" operation" (e.g. in the attribute table it is possible to zoom to each data entry separately) and an option to disable the usage of the parameter for line and polygon features "b) There shall be an option to activate the max scale also for line and polygon feature.".

As we told you during the onsite meeting, we necessary need to make different behaviors and use cases consistent by avoiding too many combinations of configurations even for maintenance purposes. Therefore, having a plugin-level configuration is our politic at the moment.

>which max zoom level is used for all zoom to extent functions (except the search service) and the "locate me" operation, when there is no search service set at all?

1. The max zoom level configuration for the Locate plugin is reported [here](https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Map) in the online documentation (it is part of the Map plugin configuration)

![image](https://user-images.githubusercontent.com/1280027/101167027-8e197180-3639-11eb-9d78-7f3e4e2d0d9f.png)

2. Because of what I wrote initially in this comment, there isn't a global configuration option for "all zoom to extent" operations. What we are able to consider now is to eventually include a configuration option from localConfig also for the Attribute Table (if you need it too) so that you are able to set the max zoom level to use for the "zoom to feature" functionality: the final zoom behaviour would be the same implemented for search services to be clear.

![image](https://user-images.githubusercontent.com/1280027/101166787-219e7280-3639-11eb-92b8-9dd68596e8b2.png)

>which max zoom level is used for all zoom to extent functions (except the search service) and the "locate me" operation, when for different search services different max zoom values are set?

There is no connection between the max zoom level option of search services and the other "zoom to" functionalities: each search service uses its own max zoom level configuration and that value isn't used elsewhere. Below is a sample of configuration to set a max zoom level for the **Locate** plugin:

```
// localConfig.json
[
    {
        "name": "Map",
        "cfg": {
            "tools": ["locate"],
            "toolsOptions": {
                "locate": {
                    "maxZoom": 5
                }
            }
        }
    },
    { "name": "Locate" }
]
```

>is the possibility to disable the max zoom level for polygon and line features implemented anywhere?

Currently no. It is a custom behavior that we cannot include in MapStore and my understanding was that you want to avoid customizations as much as possible. The current implementation of the "zoom to" functionality is aimed to properly fit the feature in the viewport by automatically setting the closest zoom level, and this is the general behavior we can maintain for the MapStore product (as I wrote above also to avoid too many combinations of configurations to be kept consistent over time).

**Comment by tdipisa** [comment]
@michegg do you have some feedback for this?

**Comment by michegg** [comment]
So to sum this up, maxZoomLevel
- for search services: is set via UI service configuration, which is stored in localConfig.json - **ok for us**
- for locate me function: is set via plugin configuration in localConfig.json - **ok for us**

- for zoom to feature: may also be configurable in localConfig.json - **yes, please implement this**

You may skip our request to disable the function for line and polygon features.

**Comment by tdipisa** [comment]
@michegg I've created https://github.com/geosolutions-it/MapStore2/issues/6287 in MS for the third point. @AGMETEOR will work on this soon.

**Comment by tdipisa** [comment]
Added new maxZoom config property for the attribute table. The updated plugin documentation is available [here](https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.FeatureEditor).

![image](https://user-images.githubusercontent.com/1280027/102083894-95e4cd00-3e14-11eb-9ec2-9396a42165b6.png)
