### ISSUE TITLE
Client ID 23 - Search Service - show GFI

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#245]
force layer visibility doesn't work --> show info doesn't work, when both options are enabled: https://github.com/geosolutions-it/austrocontrol-C125/issues/169

info button shows ""target layer is inactive"" when ""force layer…"" is disabled, although clearly active. See screenshots attached

![target layer inactive](https://user-images.githubusercontent.com/1280027/99826717-0885c400-2b59-11eb-831e-24223dd53b64.png)

![target layer inactive_settings](https://user-images.githubusercontent.com/1280027/99826725-0b80b480-2b59-11eb-9ace-cd6bf5790aa6.png)

**Comment by tdipisa** [comment]
>force layer visibility doesn't work --> show info doesn't work, when both options are enabled: #169

>info button shows ""target layer is inactive"" when ""force layer…"" is disabled, although clearly active. See screenshots attached to Mail (img)

This is probably due to the fact that the layer name was set incorrectly in the service configuration.
I've checked for example [this map](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/?#/viewer/openlayers/442) where **free:HP** is used instead of **HP** as it is for the layer in TOC, therefore MapStore is not able to find the exact matching: I think you have to pay attention when you use or not the workspace name in the GeoServer URLs

The tooltip must be improved anyway, I think.

**Comment by michegg** [comment]
Thank you, you're right. Please close this issue.
