### ISSUE TITLE
Client ID 28 - Set active tab of layer settings

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#247]
Tried: 

```
"name": "TOCItemsSettings",
                "cfg": {
                    "initialActiveTab": "style"
                }
```

Please provide information on how and where to set parameters in localConfig.

**Comment by tdipisa** [comment]
> Please provide information on how and where to set parameters in localConfig.

Also for this we will check our documentation to see if something is missing and all has been properly updated in the plugin doc.

**Comment by dsuren1** [comment]
[Documentation ](https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.TOCItemsSettings)
Could I request, to try setting the plugin config for **TOCItemsSettings** under **desktop** in the localConfig file and give it a try, as it seems to work fine at my end.
```
desktop: [
  ...,
  {
    "name": "TOCItemsSettings",
    "cfg": {
      "initialActiveTab": "style"
    }
  },
  ....
]
```

**Comment by michegg** [comment]
Thanks! Issue may be closed.
