### ISSUE TITLE
Missing catalog on the map

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/austrocontrol-C125#250]
## Description
The Catalog plugin is not present in the Burger Menu of the maps
![catalogo.JPG](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/e1aeca29-2949-4c2b-a44a-af707fd6df4c)

**How to reproduce**
- Open a map
- Click on Burger Menu

*Current Result*
The Catalog button is not present on Burger Menu

**Comment by tdipisa** [comment]
@dsuren1 I think it is a problem with your latest PR [here](https://github.com/geosolutions-it/austrocontrol-C125/pull/249). Can you please check it asap tomorrow?
