### ISSUE TITLE
Client ID 22 - Max Zoom Level of Locate tool

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#259]
Test report from @michegg.

When adding maxZoom level parameters for the locate me tool on desktop version in localConfig.json, the function itself works fine, but it somehow interferes with the annotation function. After adding the yellow marked parts it isn’t possible anymore to add geometries to an annotation by clicking into the map. Attached you find a respective GIF and our complete currently used localConfig.json.

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/907ecb36-a796-484a-9233-0aec24311edc)

![annotation](https://user-images.githubusercontent.com/1280027/104013025-206ce200-51b1-11eb-8b36-a0487315178f.gif)

The localConfig.json used by the client is available [here](https://github.com/geosolutions-it/austrocontrol-C125/files/5787006/localConfig.zip)

**Comment by MV88** [comment]
"tools": ["locate"] is causing the issue
so removing it will make the annotation work again

**Comment by michegg** [comment]
@MV88 thank you, it's working now. No need to version it.
