### ISSUE TITLE
Order of Nominatim search results

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#274]
@tdipisa commented on [Thu Apr 01 2021](https://github.com/geosolutions-it/MapStore2/issues/6731)

## Description

We have the following user feedback:

>Order of Nominatim search results: they are supposed to have priority 5, but are always shown on top, although we defined other services having priority 1

## How to reproduce

-   Search for “LOWW” in [this map](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/763)

*Expected Result*

the order of results must respect the priority configured in the service settings.

*Current Result*

The priority seems not respected in some cases. At the moment I'm not able to reproduce this in DEV using [this sample map](https://qa.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358).

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

---

@tdipisa commented on [Thu Apr 01 2021](https://github.com/geosolutions-it/MapStore2/issues/6731#issuecomment-811930543)

@MV88 any thought on this?

---

@MV88 commented on [Thu Apr 01 2021](https://github.com/geosolutions-it/MapStore2/issues/6731#issuecomment-811981453)

the problem is in the configuration

if you define a search service and you do not set the priority, this one is set to 0 [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/search.js#L77)

so the easy fix is to add "priority": 5 near "type": "nominatim" in the Search plugins in localConfig.json

usually priority for nominatim is 5, but only if this service is not defined

---

@tdipisa commented on [Mon Apr 12 2021](https://github.com/geosolutions-it/MapStore2/issues/6731#issuecomment-817685369)

@MV88 I think we simply need a PR in the c125 project to fix the configuration. I'm going to move the issue on c125 project so that you can refer it for your PR.

**Comment by ElenaGallo** [comment]
@MV88 for me the Nominatim service still has priority 1
![SS](https://user-images.githubusercontent.com/56537133/116371609-e5e48f00-a80b-11eb-8650-b131f97d54ba.png)

**Comment by MV88** [comment]
@ElenaGallo 
this is because the services that are returning a valid response have priority >= 5, which means nominatim can be the first if it the first that returns 

@michegg if you want **nominatim** always last in the list --> we can change its priority in config to a value greater than 10 which is the max configurable via UI for the other services

**Comment by michegg** [comment]
@MV88 thank you, but in case it's possible to set the priority for nominatim in localConfig.json we will set the value ourselves
