### ISSUE TITLE
CSW Catalog issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#276]
We have the following client feedback:

> The new version of MapStore doesn’t support the display of our CSW metadata. As far as we found out, the issue is related to the interpretation of the CRS of the bounding box of the CSW and this seems to be related to the fact, that the outputSchema is not used in the CSW payload of the GetRecords call (POST call).

>Currently the result from the CSW bounding box is delivered as

```
    <dc:format />
      <ows:BoundingBox crs="urn:ogc:def:crs:OGP::urn:ogc:def:crs:EPSG::21037">
        <ows:LowerCorner>39.7000 -4.6700</ows:LowerCorner>
        <ows:UpperCorner>38.4500 -3.5500</ows:UpperCorner>
      </ows:BoundingBox>
```

>MapStore seems to be unable to parse the CRS correctly.
Please try the following CSW URL for the MapStore Catalog: https://sdimdt-free.austrocontrol.at/geonetwork/csw-free/eng/csw
Also please find attached the [localConfig.json](https://app.zenhub.com/files/111421835/4e43a58f-4f99-4b7d-aa1c-62b5ef3bf3dd/download) with the JSX for the MD template to be displayed.

## Other useful information
From our DEV instance we are not able to check it because austrocontrol server is blocking the geosolutions origin: all requests containing the origin HTTP header are blocked and we get 404 Not Found.

Below some hints from the client to solve the above blocker:
- Please make sure, that your localConfig.json has entries for:

```
"proxyUrl": {
        "url": "proxy/?url=",
        "useCORS": [
            "https://sdimdt-free.austrocontrol.at/"
        ]
    },
```
- and:

```
    "authenticationRules": [
        {
            "urlPattern": "https://sdimdt-free\\.austrocontrol\\.at/.*",
            "method": "browserWithCredentials"
        },
```

- In addition to the two mentioned issues in the localConfig.json and before you can access the CSW service, you need to obtain a session cookie in your browser by opening https://sdimdt-free.austrocontrol.at and accepting the splash screen

**Comment by MV88** [comment]
@michegg I would like to know which is the SHA commit (related to this repo) which has been used to create the war deployed in here: https://sdimdt-free.austrocontrol.at/mapstore/#/

Also which is the layer that has this crs **urn:ogc:def:crs:OGP::urn:ogc:def:crs:EPSG::21037** mentioned in the issue?

**Comment by kgaeb** [comment]
- regarding the **urn:ogc:def:crs:OGP::urn:ogc:def:crs:EPSG::21037**
Actually this is the wrong CRS (sorry for confusing you with this!) - it comes from the following layer which we used for testing purpose only:
https://metadata.bgs.ac.uk/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities&
But this CSW should not be used - ours is: 
https://sdimdt-free.austrocontrol.at/geonetwork/csw-free/eng/csw?service=CSW&version=2.0.2&request=GetCapabilities
and the CRS for this is:
<dc:format>JPEG</dc:format>
      <ows:BoundingBox crs="urn:ogc:def:crs:INSPIRE RS registry::http://www.opengis.net/def/crs/EPSG/0/3857">
        <ows:LowerCorner>13.27 47.46</ows:LowerCorner>
        <ows:UpperCorner>12.56 48.13</ows:UpperCorner>
      </ows:BoundingBox>

Apologize for the confusion!

* Cookie seems to be ok
* SHA commit and repo - I need to check with Florian and will send it asap

**Comment by FlorianBruckner** [comment]
3efbeff961fa5cd59e6da70c4d6d57a1be50f19f from MapStore2 as the submodule and 
03a024b81602e06122d2a1b760853f6edaaabb1a from austrocontrol-C125.git

**Comment by MV88** [comment]
@FlorianBruckner @kgaeb @michegg

on my local environment at the commit that you have reported i have error when parsing the crs of the bbox
because we expect only the number in the CODE property

like this
```
<ows:BoundingBox crs="urn:ogc:def:crs:INSPIRE RS registry::http://www.opengis.net/def/crs/EPSG/0/3857">
   <ows:LowerCorner>13.27 47.46</ows:LowerCorner>
   <ows:UpperCorner>12.56 48.13</ows:UpperCorner>
</ows:BoundingBox>
```

in any case, in this example the coordinates of lower and upper corner are not matching the one specified in the crs
can you check if amending the bbox coordinates or the CRS with http://www.opengis.net/def/crs/EPSG/0/4326

another option would be to use EPSG as authority and fixing the mismatch

waiting to hear your feedbacks

**Comment by kgaeb** [comment]
@MV88
If I understood you correctly, I guess (and please correct me if I'm not right) that you assume that the CRS in the metadata (in our case EPSG:3857) is the CRS for the BBOX of the metadata?

That is not true:
From the ISO 19115-1 (2014):
"referenceSystemInfo --> description of the spatial and temporal reference systems used in the resource"
whereas  a resource identifies a dataset (here in our case a raster chart / WMS and the CRS is EPSG:3857 and not EPSG:4326)

"westBoundLongitude/eastBoundLongitude/southBoundLatitude/northBoundLatitude"
are always expressed in lat/lon in decimal degrees and therefore are always EPSG:4326!

Means: CRS of the resource and coordinates of the BBOX don't need to be in the same CRS.

Furthermore we have not changed the referenceSystemInfo and BBOX in our metadata since 2016 and displaying MD worked already in previous versions of MapStore.

Let me know, if I understood your comment correctly and how we should proceed to clarify the problem.
Kind regards

**Comment by tdipisa** [comment]
Dear @kgaeb 
>... Means: CRS of the resource and coordinates of the BBOX don't need to be in the same CRS.

If in MS you want to zoom to the expected extent it should be instead. I'm going to explain. MS always used the CRS reported in the metadata to know in which coordinate reference system the coordinates are expressed in order to manage them (if needed reprojecting them) according to CRS configured for the map: MS currently makes no assumptions on this because it is not possible for MS to know which is the CRS corresponding to the coordinates specified in the metadata.

>Furthermore we have not changed the referenceSystemInfo and BBOX in our metadata since 2016 and displaying MD worked already in previous versions of MapStore.

Probably in older versions of MS there was a fallback to 4326 in case the **urn** was not reconized or properly parsed: we can obviously do a check for this.

**Comment by kgaeb** [comment]
@tdipisa 
to find a way forward, would it be possible to:

- check the CRS and URN if recognized and properly parsed
--> if ok, use the CRS and coordinates of the BBOX
- if the CRS and URN **is not** recognized or properly parsed
--> check the coordinates if they fit into EPSG:4326 and use them if this check is ok

Pls let me know if this would be ok for you?

**Comment by tdipisa** [comment]
@kgaeb we are working to evaluate what is feasible MS side. We will be able to answer tomorrow. Therefore, I know @offtherailz has a further question for you about that. He will comment shortly.

**Comment by offtherailz** [comment]
Regarding the different behaviour between the master and the installed version, I verified that in the one deployed on austrocontrol servers, the piece of code (uglified) that handles the bounding box looks like this:
```javascript
if (l.boundingBox) {
                                                    var c, d = void 0, m = void 0;
                                                    if ((c = Array.isArray(l.boundingBox) ? a().head(l.boundingBox) : l.boundingBox) && c.value) {
                                                        var y, g, v, b, w, _ = null !== (y = null === (g = c.value) || void 0 === g ? void 0 : g.crs) && void 0 !== y ? y : "", x = null === (v = _.match(/[\w-]*:[\w-]*:[\w-]*:[\w-]*:[\w-]*:[^:]*:(([\w-]+\s[\w-]+)|[\w-]*)/)) || void 0 === v ? void 0 : v[0], O = (0,
                                                        f.makeNumericEPSG)(null === (b = _.match(/EPSG:[0-9]+/)) || void 0 === b ? void 0 : b[0]), E = c.value.lowerCorner, S = c.value.upperCorner, C = O || (0,
                                                        f.extractCrsFromURN)(x) || a().last(_.split(":"));
                                                        if (C) {
                                                            if ("EPSG:" === C.slice(0, 5)) {
                                                                if (!(m = (0,
                                                                f.makeNumericEPSG)(C)))
                                                                    throw new Error('No suitable EPSG numeric conversion found for "'.concat(C, '"'))
                                                            } else if (null !== (w = C.match(/\/\/www.opengis.net\/def\/crs\/EPSG\/0\/(\d+)/)) && void 0 !== w && w[0]) {
                                                                var T;
                                                                if (!(m = (0,
                                                                f.makeNumericEPSG)("EPSG:" + (null === (T = C.match(/\/\/www.opengis.net\/def\/crs\/EPSG\/0\/(\d+)/)) || void 0 === T ? void 0 : T[1]))))
                                                                    throw new Error('No suitable EPSG numeric conversion found for "'.concat(C, '"'))
                                                            } else if (!(m = (0,
                                                            f.makeNumericEPSG)("EPSG:".concat(C))))
                                                                throw new Error('No suitable EPSG numeric conversion found for "'.concat(C, '"'))
                                                        } else
                                                            m = "EPSG:4326";
                                                        "EPSG:4326" === m && "CRS84" !== C && "OGC:CRS84" !== C && (E = [E[1], E[0]],
                                                        S = [S[1], S[0]]),
                                                        d = (0,
                                                        f.makeBboxFromOWS)(E, S)
                                                    }
                                                    u.boundingBox = {
                                                        extent: d,
                                                        crs: m
                                                    }
                                                }
```

That looks very different from the one present on mapstore at the referred commit:
```javascript
if (rawRec.boundingBox) {
                                            let bbox;
                                            let crs;
                                            let el;
                                            if (Array.isArray(rawRec.boundingBox)) {
                                                el = _.head(rawRec.boundingBox);
                                            } else {
                                                el = rawRec.boundingBox;
                                            }
                                            if (el && el.value) {
                                                // EPSG:4326 is defined as (lat,lon) but mapping frameworks usually expect (lon,lat) as it is
                                                // more natural (because (lon,lat) is basically (x,y))
                                                // so internally EPSG:4326 is assumed to be (lon,lat) but when we import from external services
                                                // we assume that EPSG:4326 is (lat,lon) and CRS84 is (lon,lat) as by their definition
                                                // after conversion to (lon,lat) we set crs to EPSG:4326

                                                const crsValue = el.value?.crs ?? '';
                                                const urn = crsValue.match(/[\w-]*:[\w-]*:[\w-]*:[\w-]*:[\w-]*:[^:]*:(([\w-]+\s[\w-]+)|[\w-]*)/)?.[0];
                                                const epsg = makeNumericEPSG(crsValue.match(/EPSG:[0-9]+/)?.[0]);

                                                let lc = el.value.lowerCorner;
                                                let uc = el.value.upperCorner;

                                                const extractedCrs = epsg || (extractCrsFromURN(urn) || _.last(crsValue.split(':')));

                                                if (!extractedCrs) {
                                                    crs = 'EPSG:4326';
                                                } else if (extractedCrs.slice(0, 5) === 'EPSG:') {
                                                    crs = makeNumericEPSG(extractedCrs);
                                                    if (!crs) {
                                                        throw new Error(`No suitable EPSG numeric conversion found for "${extractedCrs}"`);
                                                    }
                                                } else {
                                                    crs = makeNumericEPSG(`EPSG:${extractedCrs}`);
                                                    if (!crs) {
                                                        throw new Error(`No suitable EPSG numeric conversion found for "${extractedCrs}"`);
                                                    }
                                                }

                                                if (crs === 'EPSG:4326' && extractedCrs !== 'CRS84' && extractedCrs !== 'OGC:CRS84') {
                                                    lc = [lc[1], lc[0]];
                                                    uc = [uc[1], uc[0]];
                                                }
                                                bbox = makeBboxFromOWS(lc, uc);
                                            }
                                            obj.boundingBox = {
                                                extent: bbox,
                                                crs
                                            };
                                        }
```

comparing the two codes, you can see in the production one there are some `C.match(/\/\/www.opengis.net\/def\/crs\/EPSG\/0\/(\d+)/)` that are not present in the one on github.

**Comment by kgaeb** [comment]
@offtherailz
regarding the versions installed at our servers:

- The public available production server is running on https://maps.austrocontrol.at - this is the version of MapStore what we got the last time from the github repo.

- The server where we are currently testing the CSW (and thats the one you investigated) has a version, where we tried to figure out what happened in the code with the CRS during loading the CSW information. This is a test system and we've not yet removed "our" version back to the github version. So this was only a test and should not be of interest to the problem in the github version.

Hope thats not causing too much confusion!

**Comment by offtherailz** [comment]
Yes, thanks, I called it "production" in error, but I meant https://sdimdt-free.austrocontrol.at/mapstore/#/ . Thank you for clarification.

**Comment by dsuren1** [comment]
> ## Other useful information
> From our DEV instance we are not able to check it because austrocontrol server is blocking the geosolutions origin: all requests containing the origin HTTP header are blocked and we get 404 Not Found.
> 
> Below some hints from the client to solve the above blocker:
> 
> * Please make sure, that your localConfig.json has entries for:
> 
> ```
> "proxyUrl": {
>         "url": "proxy/?url=",
>         "useCORS": [
>             "https://sdimdt-free.austrocontrol.at/"
>         ]
>     },
> ```
> 
> * and:
> 
> ```
>     "authenticationRules": [
>         {
>             "urlPattern": "https://sdimdt-free\\.austrocontrol\\.at/.*",
>             "method": "browserWithCredentials"
>         },
> ```
> 
> * In addition to the two mentioned issues in the localConfig.json and before you can access the CSW service, you need to obtain a session cookie in your browser by opening https://sdimdt-free.austrocontrol.at and accepting the splash screen

Hi @tdipisa 
We were able to retrieve records in a different origin (env) and provided a fix. Unfortunately we cannot test this in [Austrocontrol dev](https://austrocontrol.geo-solutions.it/), as setting the configs as mentioned results in CORS error or 404 when not.

So it would be better if we could request the client to test it directly with the fix in place. Thanks!
