### ISSUE TITLE
Aeronautical fields - Improvement

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/austrocontrol-C125#285]
**User feedback**: 

1.  Wrong formatting after deleting a value: enter 45° 10’ 10’’: the default 0-values are overwritten = OK, BUT when removing 10 for seconds and reentering ‘20’, the zero is not overwritten, but added at the end of the reentered value à user input is changed to ‘200’ instead of ‘20’, which then is reformatted to 59. This behavior is present as well for minutes and degrees input filed
2. When using decimal degrees it is not allowed at all to enter values, which are greater than the allowed value (e.g. entering 181 for longitude is blocked by the system), which is also OK
BUT it would be good to have the same solution for both options (decimal and aeronautical fields) in order to not confuse the user

**Acceptance criteria:**

1. Upon clearing the fields and entering new value, the user input should not be append with 0 (i.e clearing 10 and entering 2 should not result in 20)
2. User cannot enter value >= fields max value (Same as decimal fields)

**Comment by ElenaGallo** [comment]
@dsuren1 The entry of 180 in the decimal field is allowed even if for the aureonautics the maximum is 179. 

**How to Reproduce**
- Click on Search by coordinate
- Switch to Aeronautical
- Entering 180 (not allowed)
- Switch to Decimal
- Entering 180 (It is allowed)

**Comment by dsuren1** [comment]
@ElenaGallo That's because, in aeronautical, the user doesn't want the field to be auto formatted, so we limit the fields to their max values that's 179° 59’ 59’’

**Comment by ElenaGallo** [comment]
@dsuren1 thank you for the clarification but I noticed that, in decimal, we have a different behavior for longitude and latitude.

For latitude by entering the maximum value, in this case 90, the result is 89.9997222222 and for longitude by entering the maximum value, in this case 180, the result is 180 instead of 179.999722222

![search](https://user-images.githubusercontent.com/56537133/118665712-cdf0a180-b7f2-11eb-98d2-201307b79cf6.gif)

**Comment by dsuren1** [comment]
Hi @ElenaGallo 
This is an existing behavior and seems like it has been used to tackle drawsupport issue in Annotation
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/misc/coordinateeditors/enhancers/no90Lat.js#L3
