### ISSUE TITLE
Release v4.0

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#306]
Since we have updated the project to MS 2022.02.00 and we have completed functional tests we need to release v4.0:

- Create a new stable branch 4.x
- Update versions on it to create a tag v4.0
- Create a github release as previously done for [v3.0](https://github.com/geosolutions-it/austrocontrol-C125/releases/tag/v3.0)

**Comment by dsuren1** [comment]
**Release created**
https://github.com/geosolutions-it/austrocontrol-C125/releases/tag/v4.0

**Comment by dsuren1** [comment]
@tdipisa 
Added to the release now
