### ISSUE TITLE
mapstore-service 1.4-SNAPSHOT

### ISSUE THREAD

**Issue by FlorianBruckner** [geosolutions-it/austrocontrol-C125#308]
Hi,

trying to run a build, but it fails resolving a dependency:

```
Could not find artifact it.geosolutions.mapstore:mapstore-services:jar:1.4-SNAPSHOT in geosolutions (https://maven.geo-solutions.it)
```

I checked your public maven repository, and there is no 1.4-SNAPSHOT available. Which version do you recommend to use (there are 1.4.0, 1.4.1, 1.4.2 and 1.5-SNAPSHOT available).

@kgaeb FYI.

**Comment by FlorianBruckner** [comment]
Hi @tdipisa 

could you please take a look at this issue? I am unable to proceed with the build.

**Comment by tdipisa** [comment]
Hi @FlorianBruckner we will take care to restore it asap. I'm sorry for the late answer.

**Comment by offtherailz** [comment]
The 1.4-SNAPSHOT has been published on maven repository. You can retry.
